services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authentik -d authentik"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data

  server:
    image: ghcr.io/goauthentik/server:2025.8.4
    depends_on: [postgresql, redis]
    environment:
      AUTHENTIK_SECRET_KEY: changeme_secret_32chars_min
      AUTHENTIK_PUBLIC_URL: https://saml.lab
      DATABASE_URL: postgresql://authentik:changeme@postgresql:5432/authentik
      REDIS__HOST: redis
      REDIS__PORT: 6379
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    restart: unless-stopped

  worker:
    image: ghcr.io/goauthentik/server:2025.8.4
    command: worker
    depends_on: [postgresql, redis, server]
    environment:
      DATABASE_URL: postgresql://authentik:changeme@postgresql:5432/authentik
      REDIS__HOST: redis
      REDIS__PORT: 6379
    restart: unless-stopped
